spring:
  datasource:
    # O Render vai injetar a URL completa do Neon
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Cria as tabelas automaticamente
    properties:
      hibernate:
        # SSL é obrigatório no Neon
        ssl: true