spring:
  application:
    name: GuideAutBackend
  profiles:
    # Se não informar nada, assume "dev" (seu local com H2)
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Configuração de Email (Comum, mas senha via variável)
  mail:
    host: smtp.gmail.com
    port: 587
    username: guideautservice@gmail.com
    # Em produção, o Render vai preencher isso. Localmente, coloque no application-dev
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto

# Configurações do Actuator (Para o Ping Service não dar erro 401/403)
management:
  endpoints:
    web:
      exposure:
        include: health

# Suas configs personalizadas
jwt:
  # O Render vai injetar isso. Não deixe hardcoded aqui!
  secret: ${JWT_SECRET}
  access-minutes: 60
  refresh-days: 7

app:
  mail:
    from: guideautservice@gmail.com